// NextJS imports
import Head from "next/head";
// Component imports
import Navbar from "../components/Navbar/Navbar";
import BannerCarousel from "../components/BannerCarousel/BannerCarousel";
import DownloadApp from "../components/DownloadApp/DownloadApp";
import Description1 from "../components/Description1/Description1";
import CallToAction1 from "../components/CallToAction1/CallToAction1";
import Description2 from "../components/Description2/Description2";
import Features from "../components/Features/Features";
import AnimatedBg from "../components/AnimatedBg/AnimatedBg";
import CallToAction2 from "../components/CallToAction2/CallToAction2";
import OurTeam from "../components/OurTeam/OurTeam";
import Testimonials from "../components/Testimonials/Testimonials";
import FrequentlyAskedQuestions from "../components/FAQ/FrequentlyAskedQuestions";
import ContactUs from "../components/ContactUs/ContactUs";
import FooterNav from "../components/FooterNav/FooterNav";
import Copyright from "../components/Copyright/Copyright";

export default function Home() {
  return (
    <>
      <Head>
        <title>Splash | Internship Project 1</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo-sm-splash.png" />
      </Head>

      <header>
        <Navbar />
        <BannerCarousel />
      </header>

      <main>
        <section className="container">
          <DownloadApp />
          <Description1 />
          <CallToAction1 />
          <Description2 />
        </section>

        <section className="container">
          <Features />
        </section>

        <section>
          <AnimatedBg />
          <CallToAction2 />
        </section>

        <section className="container">
          <OurTeam />
          <Testimonials />
        </section>

        <section>
          <FrequentlyAskedQuestions />
        </section>

        <section className="container">
          <ContactUs />
        </section>
      </main>

      <footer>
        <FooterNav />
        <Copyright />
      </footer>
    </>
  );
}
