// NextJS imports
import Head from "next/head";
// Styles imports
import styles from "../styles/Home.module.scss";
// Component imports
import Navbar from "../components/Navbar/Navbar";
import BannerCarousel from "../components/BannerCarousel/BannerCarousel";
import DownloadApp from "../components/DownloadApp/DownloadApp";
import Description1 from "../components/Description1/Description1";
import CallToAction1 from "../components/CallToAction1/CallToAction1";
import Description2 from "../components/Description2/Description2";

export default function Home() {


  return (
    <>
      <Head>
        <title>Splash | Internship Project 1</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header>
        <Navbar />
        <BannerCarousel />
      </header>

      <main>
        <section className="container">
          <DownloadApp />
          <Description1 />
          <CallToAction1 />
          <Description2 />
        </section>

        {/* <section>
          <Features />
        </section>

        <section>
          <AnimatedBg />
          <CallToAction2 />
        </section>

        <section>
          <OurTeam />
          <Testimonials />
        </section>

        <section>
          <FrequentlyAskedQuestions />
        </section>

        <section>
          <ContactUs />
        </section> */}
      </main>

      {/* <footer>
        <FooterNav />
        <Footer />
      </footer> */}
    </>
  );
}
